using System;
using System.Collections.Generic;
using System.IO.IsolatedStorage;
using System.Linq;
using System.Numerics;
using System.Text;
using System.Threading.Tasks;

namespace CodeWars._5kyu
{
    /*
     * Fibonacci numbers are generated by setting F0 = 0, F1 = 1, and then using the formula:
     * Fn = Fn-1 + Fn-2
     * Your task is to efficiently calculate the nth element in the Fibonacci sequence and
     * then count the occurrence of each digit in the number.
     * Return a list of integer pairs sorted in descending order.
     */
    internal class CalculateFibReturnDigitPccurrencesCount
    {
        public static List<Tuple<int, int>> FibDigits(int n)
        {
            BigInteger fib = Fib(n);
            Dictionary<int, int> map = GetFibDictionaryDigits(fib);
            return map.Select(x => new Tuple<int, int>(x.Value, x.Key)).ToList();

        }
        static BigInteger Fib(int n)
        {
            if (n == 0 || n == 1)
                return n;
            BigInteger[] integers = new BigInteger[n + 1];
            long[] ar = new long[n+1];
            ar[0] = 0;
            ar[1] = 1;
            integers[0] = BigInteger.Zero;
            integers[1] = BigInteger.One;
            for (int i = 2; i <= n; i++)
                integers[i] = integers[i - 2] + integers[i - 1];
            return integers[n];
        }
        static Dictionary<int, int> GetFibDictionaryDigits(BigInteger fibNumber)
        {
            Dictionary<int, int> fibDictionary = new Dictionary<int, int>();
            while (fibNumber > 0)
            {
                int key = (int) (fibNumber % 10);
                fibNumber /= 10;
                if (!fibDictionary.ContainsKey(key))
                    fibDictionary.Add(key, 1);
                else
                    fibDictionary[key]++;
            }
            return fibDictionary.OrderByDescending(x => x.Value).ThenByDescending(x => x.Key).ToDictionary(x => x.Key, x => x.Value);
        }

    }
}
